// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lottery/lottery/event.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type EvtSystemInfoUpdated struct {
	SystemInfo *SystemInfo `protobuf:"bytes,1,opt,name=systemInfo,proto3" json:"systemInfo,omitempty"`
}

func (m *EvtSystemInfoUpdated) Reset()         { *m = EvtSystemInfoUpdated{} }
func (m *EvtSystemInfoUpdated) String() string { return proto.CompactTextString(m) }
func (*EvtSystemInfoUpdated) ProtoMessage()    {}
func (*EvtSystemInfoUpdated) Descriptor() ([]byte, []int) {
	return fileDescriptor_85234cf93f0f7904, []int{0}
}
func (m *EvtSystemInfoUpdated) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EvtSystemInfoUpdated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EvtSystemInfoUpdated.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EvtSystemInfoUpdated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvtSystemInfoUpdated.Merge(m, src)
}
func (m *EvtSystemInfoUpdated) XXX_Size() int {
	return m.Size()
}
func (m *EvtSystemInfoUpdated) XXX_DiscardUnknown() {
	xxx_messageInfo_EvtSystemInfoUpdated.DiscardUnknown(m)
}

var xxx_messageInfo_EvtSystemInfoUpdated proto.InternalMessageInfo

func (m *EvtSystemInfoUpdated) GetSystemInfo() *SystemInfo {
	if m != nil {
		return m.SystemInfo
	}
	return nil
}

type EvtLotteryBegan struct {
	Lottery *Lottery `protobuf:"bytes,1,opt,name=lottery,proto3" json:"lottery,omitempty"`
}

func (m *EvtLotteryBegan) Reset()         { *m = EvtLotteryBegan{} }
func (m *EvtLotteryBegan) String() string { return proto.CompactTextString(m) }
func (*EvtLotteryBegan) ProtoMessage()    {}
func (*EvtLotteryBegan) Descriptor() ([]byte, []int) {
	return fileDescriptor_85234cf93f0f7904, []int{1}
}
func (m *EvtLotteryBegan) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EvtLotteryBegan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EvtLotteryBegan.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EvtLotteryBegan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvtLotteryBegan.Merge(m, src)
}
func (m *EvtLotteryBegan) XXX_Size() int {
	return m.Size()
}
func (m *EvtLotteryBegan) XXX_DiscardUnknown() {
	xxx_messageInfo_EvtLotteryBegan.DiscardUnknown(m)
}

var xxx_messageInfo_EvtLotteryBegan proto.InternalMessageInfo

func (m *EvtLotteryBegan) GetLottery() *Lottery {
	if m != nil {
		return m.Lottery
	}
	return nil
}

type EvtLotteryEnded struct {
	Lottery *Lottery `protobuf:"bytes,1,opt,name=lottery,proto3" json:"lottery,omitempty"`
}

func (m *EvtLotteryEnded) Reset()         { *m = EvtLotteryEnded{} }
func (m *EvtLotteryEnded) String() string { return proto.CompactTextString(m) }
func (*EvtLotteryEnded) ProtoMessage()    {}
func (*EvtLotteryEnded) Descriptor() ([]byte, []int) {
	return fileDescriptor_85234cf93f0f7904, []int{2}
}
func (m *EvtLotteryEnded) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EvtLotteryEnded) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EvtLotteryEnded.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EvtLotteryEnded) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvtLotteryEnded.Merge(m, src)
}
func (m *EvtLotteryEnded) XXX_Size() int {
	return m.Size()
}
func (m *EvtLotteryEnded) XXX_DiscardUnknown() {
	xxx_messageInfo_EvtLotteryEnded.DiscardUnknown(m)
}

var xxx_messageInfo_EvtLotteryEnded proto.InternalMessageInfo

func (m *EvtLotteryEnded) GetLottery() *Lottery {
	if m != nil {
		return m.Lottery
	}
	return nil
}

type EvtCreateBet struct {
	LotteryId string     `protobuf:"bytes,1,opt,name=lotteryId,proto3" json:"lotteryId,omitempty"`
	BetIndex  int64      `protobuf:"varint,2,opt,name=betIndex,proto3" json:"betIndex,omitempty"`
	Creator   string     `protobuf:"bytes,3,opt,name=creator,proto3" json:"creator,omitempty"`
	Amount    types.Coin `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount"`
	At        int64      `protobuf:"varint,5,opt,name=at,proto3" json:"at,omitempty"`
}

func (m *EvtCreateBet) Reset()         { *m = EvtCreateBet{} }
func (m *EvtCreateBet) String() string { return proto.CompactTextString(m) }
func (*EvtCreateBet) ProtoMessage()    {}
func (*EvtCreateBet) Descriptor() ([]byte, []int) {
	return fileDescriptor_85234cf93f0f7904, []int{3}
}
func (m *EvtCreateBet) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EvtCreateBet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EvtCreateBet.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EvtCreateBet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvtCreateBet.Merge(m, src)
}
func (m *EvtCreateBet) XXX_Size() int {
	return m.Size()
}
func (m *EvtCreateBet) XXX_DiscardUnknown() {
	xxx_messageInfo_EvtCreateBet.DiscardUnknown(m)
}

var xxx_messageInfo_EvtCreateBet proto.InternalMessageInfo

func (m *EvtCreateBet) GetLotteryId() string {
	if m != nil {
		return m.LotteryId
	}
	return ""
}

func (m *EvtCreateBet) GetBetIndex() int64 {
	if m != nil {
		return m.BetIndex
	}
	return 0
}

func (m *EvtCreateBet) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *EvtCreateBet) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

func (m *EvtCreateBet) GetAt() int64 {
	if m != nil {
		return m.At
	}
	return 0
}

func init() {
	proto.RegisterType((*EvtSystemInfoUpdated)(nil), "lottery.lottery.EvtSystemInfoUpdated")
	proto.RegisterType((*EvtLotteryBegan)(nil), "lottery.lottery.EvtLotteryBegan")
	proto.RegisterType((*EvtLotteryEnded)(nil), "lottery.lottery.EvtLotteryEnded")
	proto.RegisterType((*EvtCreateBet)(nil), "lottery.lottery.EvtCreateBet")
}

func init() { proto.RegisterFile("lottery/lottery/event.proto", fileDescriptor_85234cf93f0f7904) }

var fileDescriptor_85234cf93f0f7904 = []byte{
	// 385 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xb1, 0x6e, 0xe2, 0x40,
	0x10, 0x86, 0x6d, 0xe0, 0xb8, 0x63, 0xef, 0x74, 0x48, 0x16, 0xd2, 0x19, 0xb8, 0xf3, 0x11, 0x2a,
	0x9a, 0xd8, 0x82, 0x14, 0x29, 0x52, 0xc5, 0xc8, 0x05, 0x52, 0x2a, 0xa3, 0x34, 0x69, 0xd0, 0x9a,
	0x1d, 0x2c, 0x4b, 0x61, 0x17, 0x79, 0x27, 0x16, 0xbc, 0x45, 0x1e, 0x26, 0xaf, 0x10, 0x89, 0x12,
	0xa5, 0x4a, 0x15, 0x45, 0xf0, 0x22, 0x91, 0xed, 0x35, 0x24, 0xa4, 0x4b, 0xb5, 0x9e, 0xf9, 0xbf,
	0xf9, 0x67, 0xac, 0x9f, 0xb4, 0x6f, 0x05, 0x22, 0xc4, 0x2b, 0xa7, 0x78, 0x21, 0x01, 0x8e, 0xf6,
	0x22, 0x16, 0x28, 0x8c, 0xba, 0x6a, 0xda, 0xea, 0x6d, 0x35, 0x42, 0x11, 0x8a, 0x4c, 0x73, 0xd2,
	0xaf, 0x1c, 0x6b, 0x35, 0xa7, 0x42, 0xce, 0x85, 0x9c, 0xe4, 0x42, 0x5e, 0x28, 0xc9, 0xca, 0x2b,
	0x27, 0xa0, 0x12, 0x9c, 0xa4, 0x1f, 0x00, 0xd2, 0xbe, 0x33, 0x15, 0x11, 0x57, 0xfa, 0xc9, 0xf1,
	0x7a, 0xb9, 0x92, 0x08, 0xf3, 0x49, 0xc4, 0x67, 0x85, 0xfb, 0xbf, 0x63, 0xa4, 0x38, 0x2a, 0x93,
	0xbb, 0x63, 0xd2, 0xf0, 0x12, 0x1c, 0x67, 0x63, 0x23, 0x3e, 0x13, 0xd7, 0x0b, 0x46, 0x11, 0x98,
	0x71, 0x41, 0x88, 0xdc, 0x37, 0x4d, 0xbd, 0xa3, 0xf7, 0x7e, 0x0e, 0xda, 0xf6, 0xd1, 0x0f, 0xd9,
	0x87, 0x39, 0xff, 0x1d, 0xde, 0xf5, 0x48, 0xdd, 0x4b, 0xf0, 0x2a, 0x87, 0x5c, 0x08, 0x29, 0x37,
	0x06, 0xe4, 0xbb, 0x1a, 0x52, 0x66, 0xe6, 0x27, 0x33, 0xc5, 0xfb, 0x05, 0xf8, 0xd1, 0xc6, 0xe3,
	0x0c, 0xd8, 0x97, 0x6c, 0x1e, 0x75, 0xf2, 0xcb, 0x4b, 0x70, 0x18, 0x03, 0x45, 0x70, 0x01, 0x8d,
	0xbf, 0xa4, 0xa6, 0xb4, 0x11, 0xcb, 0x6c, 0x6a, 0xfe, 0xa1, 0x61, 0xb4, 0xc8, 0x8f, 0x00, 0x70,
	0xc4, 0x19, 0x2c, 0xcd, 0x52, 0x47, 0xef, 0x95, 0xfd, 0x7d, 0x9d, 0xae, 0x9f, 0xa6, 0x36, 0x22,
	0x36, 0xcb, 0xe9, 0x9c, 0x6b, 0x3e, 0x3d, 0x9c, 0x36, 0x54, 0x64, 0x97, 0x8c, 0xc5, 0x20, 0xe5,
	0x18, 0xe3, 0x88, 0x87, 0x7e, 0x01, 0x1a, 0xe7, 0xa4, 0x4a, 0xe7, 0xe2, 0x8e, 0xa3, 0x59, 0xc9,
	0x2e, 0x6e, 0xda, 0x8a, 0x4f, 0x43, 0xb5, 0x55, 0xa8, 0xf6, 0x50, 0x44, 0xdc, 0xad, 0xac, 0x5f,
	0xfe, 0x6b, 0xbe, 0xc2, 0x8d, 0xdf, 0xa4, 0x44, 0xd1, 0xfc, 0x96, 0x9d, 0x50, 0xa2, 0xe8, 0xf6,
	0xd7, 0x5b, 0x4b, 0xdf, 0x6c, 0x2d, 0xfd, 0x75, 0x6b, 0xe9, 0xf7, 0x3b, 0x4b, 0xdb, 0xec, 0x2c,
	0xed, 0x79, 0x67, 0x69, 0x37, 0x7f, 0x8a, 0x6c, 0x97, 0xfb, 0x94, 0x71, 0xb5, 0x00, 0x19, 0x54,
	0xb3, 0x90, 0xcf, 0xde, 0x02, 0x00, 0x00, 0xff, 0xff, 0x97, 0xca, 0x21, 0x1f, 0xa7, 0x02, 0x00,
	0x00,
}

func (m *EvtSystemInfoUpdated) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EvtSystemInfoUpdated) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EvtSystemInfoUpdated) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SystemInfo != nil {
		{
			size, err := m.SystemInfo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EvtLotteryBegan) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EvtLotteryBegan) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EvtLotteryBegan) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Lottery != nil {
		{
			size, err := m.Lottery.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EvtLotteryEnded) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EvtLotteryEnded) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EvtLotteryEnded) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Lottery != nil {
		{
			size, err := m.Lottery.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EvtCreateBet) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EvtCreateBet) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EvtCreateBet) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.At != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.At))
		i--
		dAtA[i] = 0x28
	}
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x1a
	}
	if m.BetIndex != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.BetIndex))
		i--
		dAtA[i] = 0x10
	}
	if len(m.LotteryId) > 0 {
		i -= len(m.LotteryId)
		copy(dAtA[i:], m.LotteryId)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.LotteryId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvent(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvent(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EvtSystemInfoUpdated) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SystemInfo != nil {
		l = m.SystemInfo.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	return n
}

func (m *EvtLotteryBegan) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Lottery != nil {
		l = m.Lottery.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	return n
}

func (m *EvtLotteryEnded) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Lottery != nil {
		l = m.Lottery.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	return n
}

func (m *EvtCreateBet) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.LotteryId)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.BetIndex != 0 {
		n += 1 + sovEvent(uint64(m.BetIndex))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovEvent(uint64(l))
	if m.At != 0 {
		n += 1 + sovEvent(uint64(m.At))
	}
	return n
}

func sovEvent(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvent(x uint64) (n int) {
	return sovEvent(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EvtSystemInfoUpdated) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EvtSystemInfoUpdated: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EvtSystemInfoUpdated: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SystemInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SystemInfo == nil {
				m.SystemInfo = &SystemInfo{}
			}
			if err := m.SystemInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EvtLotteryBegan) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EvtLotteryBegan: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EvtLotteryBegan: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lottery", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Lottery == nil {
				m.Lottery = &Lottery{}
			}
			if err := m.Lottery.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EvtLotteryEnded) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EvtLotteryEnded: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EvtLotteryEnded: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lottery", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Lottery == nil {
				m.Lottery = &Lottery{}
			}
			if err := m.Lottery.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EvtCreateBet) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EvtCreateBet: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EvtCreateBet: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LotteryId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LotteryId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BetIndex", wireType)
			}
			m.BetIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BetIndex |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field At", wireType)
			}
			m.At = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.At |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvent(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvent
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvent
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvent
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvent        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvent          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvent = fmt.Errorf("proto: unexpected end of group")
)
