// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lottery/lottery/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateBet struct {
	Creator string     `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Amount  types.Coin `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount"`
}

func (m *MsgCreateBet) Reset()         { *m = MsgCreateBet{} }
func (m *MsgCreateBet) String() string { return proto.CompactTextString(m) }
func (*MsgCreateBet) ProtoMessage()    {}
func (*MsgCreateBet) Descriptor() ([]byte, []int) {
	return fileDescriptor_205524380119aaf6, []int{0}
}
func (m *MsgCreateBet) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateBet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateBet.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateBet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateBet.Merge(m, src)
}
func (m *MsgCreateBet) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateBet) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateBet.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateBet proto.InternalMessageInfo

func (m *MsgCreateBet) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateBet) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

type MsgCreateBetResponse struct {
	LotteryId string `protobuf:"bytes,1,opt,name=lotteryId,proto3" json:"lotteryId,omitempty"`
	BetIndex  int64  `protobuf:"varint,2,opt,name=betIndex,proto3" json:"betIndex,omitempty"`
}

func (m *MsgCreateBetResponse) Reset()         { *m = MsgCreateBetResponse{} }
func (m *MsgCreateBetResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateBetResponse) ProtoMessage()    {}
func (*MsgCreateBetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_205524380119aaf6, []int{1}
}
func (m *MsgCreateBetResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateBetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateBetResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateBetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateBetResponse.Merge(m, src)
}
func (m *MsgCreateBetResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateBetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateBetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateBetResponse proto.InternalMessageInfo

func (m *MsgCreateBetResponse) GetLotteryId() string {
	if m != nil {
		return m.LotteryId
	}
	return ""
}

func (m *MsgCreateBetResponse) GetBetIndex() int64 {
	if m != nil {
		return m.BetIndex
	}
	return 0
}

type MsgUpdateSystemInfo struct {
	Creator  string      `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Fee      *types.Coin `protobuf:"bytes,2,opt,name=fee,proto3" json:"fee,omitempty"`
	MinBet   *types.Coin `protobuf:"bytes,3,opt,name=minBet,proto3" json:"minBet,omitempty"`
	MaxBet   *types.Coin `protobuf:"bytes,4,opt,name=maxBet,proto3" json:"maxBet,omitempty"`
	BetCount int64       `protobuf:"varint,5,opt,name=betCount,proto3" json:"betCount,omitempty"`
}

func (m *MsgUpdateSystemInfo) Reset()         { *m = MsgUpdateSystemInfo{} }
func (m *MsgUpdateSystemInfo) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateSystemInfo) ProtoMessage()    {}
func (*MsgUpdateSystemInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_205524380119aaf6, []int{2}
}
func (m *MsgUpdateSystemInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateSystemInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateSystemInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateSystemInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateSystemInfo.Merge(m, src)
}
func (m *MsgUpdateSystemInfo) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateSystemInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateSystemInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateSystemInfo proto.InternalMessageInfo

func (m *MsgUpdateSystemInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdateSystemInfo) GetFee() *types.Coin {
	if m != nil {
		return m.Fee
	}
	return nil
}

func (m *MsgUpdateSystemInfo) GetMinBet() *types.Coin {
	if m != nil {
		return m.MinBet
	}
	return nil
}

func (m *MsgUpdateSystemInfo) GetMaxBet() *types.Coin {
	if m != nil {
		return m.MaxBet
	}
	return nil
}

func (m *MsgUpdateSystemInfo) GetBetCount() int64 {
	if m != nil {
		return m.BetCount
	}
	return 0
}

type MsgUpdateSystemInfoResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (m *MsgUpdateSystemInfoResponse) Reset()         { *m = MsgUpdateSystemInfoResponse{} }
func (m *MsgUpdateSystemInfoResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateSystemInfoResponse) ProtoMessage()    {}
func (*MsgUpdateSystemInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_205524380119aaf6, []int{3}
}
func (m *MsgUpdateSystemInfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateSystemInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateSystemInfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateSystemInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateSystemInfoResponse.Merge(m, src)
}
func (m *MsgUpdateSystemInfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateSystemInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateSystemInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateSystemInfoResponse proto.InternalMessageInfo

func (m *MsgUpdateSystemInfoResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*MsgCreateBet)(nil), "lottery.lottery.MsgCreateBet")
	proto.RegisterType((*MsgCreateBetResponse)(nil), "lottery.lottery.MsgCreateBetResponse")
	proto.RegisterType((*MsgUpdateSystemInfo)(nil), "lottery.lottery.MsgUpdateSystemInfo")
	proto.RegisterType((*MsgUpdateSystemInfoResponse)(nil), "lottery.lottery.MsgUpdateSystemInfoResponse")
}

func init() { proto.RegisterFile("lottery/lottery/tx.proto", fileDescriptor_205524380119aaf6) }

var fileDescriptor_205524380119aaf6 = []byte{
	// 424 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xcd, 0xca, 0xd3, 0x40,
	0x14, 0xcd, 0x98, 0xcf, 0x7e, 0xed, 0x28, 0x28, 0xb1, 0x60, 0x1a, 0x35, 0x96, 0xa0, 0x50, 0x50,
	0x13, 0x52, 0x17, 0x5d, 0x9b, 0xae, 0xba, 0x28, 0x68, 0x8a, 0x1b, 0x37, 0x92, 0x9f, 0xdb, 0x10,
	0x30, 0x33, 0x21, 0x33, 0x95, 0x14, 0x5f, 0xc2, 0x87, 0xf1, 0x01, 0x5c, 0x76, 0x59, 0x5c, 0xb9,
	0x12, 0x69, 0x5f, 0xc2, 0xa5, 0x64, 0x32, 0x49, 0x4b, 0x2d, 0x56, 0x5c, 0x4d, 0xce, 0x9c, 0x73,
	0x73, 0xe6, 0xdc, 0xb9, 0x83, 0xf5, 0x0f, 0x94, 0x73, 0x28, 0xd6, 0x4e, 0xb3, 0xf2, 0xd2, 0xce,
	0x0b, 0xca, 0xa9, 0x76, 0x47, 0xee, 0xd8, 0x72, 0x35, 0xfa, 0x09, 0x4d, 0xa8, 0xe0, 0x9c, 0xea,
	0xab, 0x96, 0x19, 0x83, 0x88, 0xb2, 0x8c, 0xb2, 0xf7, 0x35, 0x51, 0x03, 0x49, 0x99, 0x35, 0x72,
	0xc2, 0x80, 0x81, 0xf3, 0xd1, 0x0d, 0x81, 0x07, 0xae, 0x13, 0xd1, 0x94, 0xd4, 0xbc, 0xf5, 0x09,
	0xdf, 0x9e, 0xb3, 0x64, 0x5a, 0x40, 0xc0, 0xc1, 0x03, 0xae, 0x8d, 0xf1, 0x75, 0x54, 0x01, 0x5a,
	0xe8, 0x68, 0x88, 0x46, 0x3d, 0x4f, 0xff, 0xf6, 0xe5, 0x45, 0x5f, 0xfe, 0xf2, 0x55, 0x1c, 0x17,
	0xc0, 0xd8, 0x82, 0x17, 0x29, 0x49, 0xfc, 0x46, 0xa8, 0x4d, 0x70, 0x27, 0xc8, 0xe8, 0x8a, 0x70,
	0xfd, 0xc6, 0x10, 0x8d, 0x6e, 0x8d, 0x07, 0xb6, 0xd4, 0x57, 0xa6, 0xb6, 0x34, 0xb5, 0xa7, 0x34,
	0x25, 0xde, 0xd5, 0xe6, 0xc7, 0x63, 0xc5, 0x97, 0x72, 0xeb, 0x35, 0xee, 0x1f, 0x9b, 0xfb, 0xc0,
	0x72, 0x4a, 0x18, 0x68, 0x0f, 0x71, 0x4f, 0x06, 0x9e, 0xc5, 0xf5, 0x31, 0xfc, 0xc3, 0x86, 0x66,
	0xe0, 0x6e, 0x08, 0x7c, 0x46, 0x62, 0x28, 0x85, 0xa1, 0xea, 0xb7, 0xd8, 0xfa, 0x85, 0xf0, 0xbd,
	0x39, 0x4b, 0xde, 0xe6, 0x71, 0xc0, 0x61, 0xb1, 0x66, 0x1c, 0xb2, 0x19, 0x59, 0xd2, 0xff, 0x8a,
	0xf5, 0x0c, 0xab, 0x4b, 0x80, 0x8b, 0x99, 0xfc, 0x4a, 0xa5, 0xb9, 0xb8, 0x93, 0xa5, 0xc4, 0x03,
	0xae, 0xab, 0x97, 0xf4, 0x52, 0x28, 0x4a, 0x82, 0xb2, 0x2a, 0xb9, 0xba, 0x5c, 0x22, 0x84, 0x32,
	0xfa, 0x54, 0xf4, 0xfa, 0x66, 0x1b, 0x5d, 0x60, 0x6b, 0x82, 0x1f, 0x9c, 0x49, 0xde, 0xf6, 0x54,
	0xc7, 0xd7, 0x6c, 0x15, 0x45, 0xc0, 0x98, 0xe8, 0x40, 0xd7, 0x6f, 0xe0, 0xf8, 0x2b, 0xc2, 0xea,
	0x9c, 0x25, 0xda, 0x1b, 0xdc, 0x3b, 0xcc, 0xc1, 0x23, 0xfb, 0x64, 0xf4, 0xec, 0xe3, 0x9b, 0x32,
	0x9e, 0xfe, 0x95, 0x6e, 0x4d, 0x97, 0xf8, 0xee, 0x1f, 0x57, 0xf1, 0xe4, 0x5c, 0xe9, 0xa9, 0xca,
	0x78, 0xfe, 0x2f, 0xaa, 0xc6, 0xc7, 0x73, 0x37, 0x3b, 0x13, 0x6d, 0x77, 0x26, 0xfa, 0xb9, 0x33,
	0xd1, 0xe7, 0xbd, 0xa9, 0x6c, 0xf7, 0xa6, 0xf2, 0x7d, 0x6f, 0x2a, 0xef, 0xee, 0x37, 0x6f, 0xaa,
	0x3c, 0xbc, 0xae, 0x75, 0x0e, 0x2c, 0xec, 0x88, 0xf9, 0x7f, 0xf9, 0x3b, 0x00, 0x00, 0xff, 0xff,
	0xf8, 0x4a, 0xbd, 0x0b, 0x7d, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreateBet(ctx context.Context, in *MsgCreateBet, opts ...grpc.CallOption) (*MsgCreateBetResponse, error)
	UpdateSystemInfo(ctx context.Context, in *MsgUpdateSystemInfo, opts ...grpc.CallOption) (*MsgUpdateSystemInfoResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateBet(ctx context.Context, in *MsgCreateBet, opts ...grpc.CallOption) (*MsgCreateBetResponse, error) {
	out := new(MsgCreateBetResponse)
	err := c.cc.Invoke(ctx, "/lottery.lottery.Msg/CreateBet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateSystemInfo(ctx context.Context, in *MsgUpdateSystemInfo, opts ...grpc.CallOption) (*MsgUpdateSystemInfoResponse, error) {
	out := new(MsgUpdateSystemInfoResponse)
	err := c.cc.Invoke(ctx, "/lottery.lottery.Msg/UpdateSystemInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreateBet(context.Context, *MsgCreateBet) (*MsgCreateBetResponse, error)
	UpdateSystemInfo(context.Context, *MsgUpdateSystemInfo) (*MsgUpdateSystemInfoResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateBet(ctx context.Context, req *MsgCreateBet) (*MsgCreateBetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBet not implemented")
}
func (*UnimplementedMsgServer) UpdateSystemInfo(ctx context.Context, req *MsgUpdateSystemInfo) (*MsgUpdateSystemInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSystemInfo not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateBet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lottery.lottery.Msg/CreateBet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateBet(ctx, req.(*MsgCreateBet))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateSystemInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateSystemInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateSystemInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lottery.lottery.Msg/UpdateSystemInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateSystemInfo(ctx, req.(*MsgUpdateSystemInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lottery.lottery.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBet",
			Handler:    _Msg_CreateBet_Handler,
		},
		{
			MethodName: "UpdateSystemInfo",
			Handler:    _Msg_UpdateSystemInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lottery/lottery/tx.proto",
}

func (m *MsgCreateBet) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateBet) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateBet) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateBetResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateBetResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateBetResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BetIndex != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.BetIndex))
		i--
		dAtA[i] = 0x10
	}
	if len(m.LotteryId) > 0 {
		i -= len(m.LotteryId)
		copy(dAtA[i:], m.LotteryId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.LotteryId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateSystemInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateSystemInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateSystemInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BetCount != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.BetCount))
		i--
		dAtA[i] = 0x28
	}
	if m.MaxBet != nil {
		{
			size, err := m.MaxBet.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.MinBet != nil {
		{
			size, err := m.MinBet.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Fee != nil {
		{
			size, err := m.Fee.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateSystemInfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateSystemInfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateSystemInfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Success {
		i--
		if m.Success {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateBet) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgCreateBetResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.LotteryId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.BetIndex != 0 {
		n += 1 + sovTx(uint64(m.BetIndex))
	}
	return n
}

func (m *MsgUpdateSystemInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Fee != nil {
		l = m.Fee.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	if m.MinBet != nil {
		l = m.MinBet.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	if m.MaxBet != nil {
		l = m.MaxBet.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	if m.BetCount != 0 {
		n += 1 + sovTx(uint64(m.BetCount))
	}
	return n
}

func (m *MsgUpdateSystemInfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Success {
		n += 2
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateBet) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateBet: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateBet: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateBetResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateBetResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateBetResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LotteryId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LotteryId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BetIndex", wireType)
			}
			m.BetIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BetIndex |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateSystemInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateSystemInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateSystemInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Fee == nil {
				m.Fee = &types.Coin{}
			}
			if err := m.Fee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinBet", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.MinBet == nil {
				m.MinBet = &types.Coin{}
			}
			if err := m.MinBet.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxBet", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.MaxBet == nil {
				m.MaxBet = &types.Coin{}
			}
			if err := m.MaxBet.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BetCount", wireType)
			}
			m.BetCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BetCount |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateSystemInfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateSystemInfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateSystemInfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Success", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Success = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
